language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t kasperkowalski/tutorial-docker-1 -f Dockerfile.dev .

script:
  - docker run -e CI=true kasperkowalski/tutorial-docker-1 npm run test